# Generated by Django 4.2.8 on 2024-06-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_deny', models.IntegerField(default=0)),
                ('join_way', models.TextField(default=None)),
                ('spcl_cnd', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('cb_name', models.TextField()),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('crdt_prdt_type', models.IntegerField()),
                ('join_way', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_deny', models.IntegerField(default=0)),
                ('join_way', models.TextField(default=None)),
                ('spcl_cnd', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(default=None, max_length=100)),
                ('intr_rate', models.FloatField(default=0, null=True)),
                ('intr_rate2', models.FloatField(default=0, null=True)),
                ('save_trm', models.IntegerField(default=0, null=True)),
                ('rsrv_type_nm', models.TextField(default=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type_nm', models.TextField()),
                ('crdt_grad_1', models.FloatField(default=0, null=True)),
                ('crdt_grad_4', models.FloatField(default=0, null=True)),
                ('crdt_grad_5', models.FloatField(default=0, null=True)),
                ('crdt_grad_6', models.FloatField(default=0, null=True)),
                ('crdt_grad_10', models.FloatField(default=0, null=True)),
                ('crdt_grad_11', models.FloatField(default=0, null=True)),
                ('crdt_grad_12', models.FloatField(default=0, null=True)),
                ('crdt_grad_13', models.FloatField(default=0, null=True)),
                ('crdt_grad_avg', models.FloatField(default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.loanproducts')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(default=None, max_length=100)),
                ('intr_rate', models.FloatField(default=0, null=True)),
                ('intr_rate2', models.FloatField(default=0, null=True)),
                ('save_trm', models.IntegerField(default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.depositproducts')),
            ],
        ),
    ]
